package laba_9;

import java.awt.Font;
import java.io.*;
import java.util.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.FontUIResource;

public class NewJFrame extends javax.swing.JFrame {

    private static String encoding = "Cp1251";
   // private static PrintStream toyOut = System.out;
    //static final String filename;
    //static final String filenameBak;
    //static final String idxname;
   // static final String idxnameBak;
	    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() 
    {
        initComponents();
    }
    public boolean zipped = false;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jOptionPane1 = new javax.swing.JOptionPane();
        jDialog4 = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Выполнить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Добавить данные", "Добавление сжатых данных", "Очистить все данные", "Очистить данные по ключу", "Печать несортированных данных", "Распечатать отсортированные данные по ключу", "Печать данных в обратном порядке отсортированных по ключу", "Найти запись по ключу", "Найти запись > ключу", "Найти запись < ключу", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Дата поступления", "Поставщик", "Возрастные ограничения" }));

        jLabel9.setText("Ключ");

        jLabel1.setText("Способы обработки данных");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("Файл");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("Change file name");
        jRadioButtonMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem4);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Exit");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("View");

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("Font");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem3);

        jMenu4.setText("Look and Feel");
        jMenu4.setHideActionText(true);
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenu4MouseEntered(evt);
            }
        });
        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("About");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1))
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        //System.exit(0);
        int response = JOptionPane.showConfirmDialog(this, "Хотите выйти?");
    	if (response == JOptionPane.YES_OPTION) System.exit(0);
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        //JOptionPane.showMessageDialog(this,"Козунов Алексей Леонидович, 2 курс, 13 группа, ФПМИ, БГУ");
        JOptionPane.showMessageDialog(this, "<html><h2>Условие задачи:</h2>"
    				+ "<p>Учётная запись торговой фирмы имеет атрибуты: код игрушки, название "
    				+ "игрушки, возрастные границы (например, 10-15), цена за единицу,</p>"
    				+ "<p>количество в наличии, дата поступления, поставщик. Индексировать по дата</p>"
                                + "<p>поступления, поставщик, возрастные границы.</p>"
    				+ "<h2>Информация о разработчике:</h2><p>Козунов Алексей Леонидович, 2 курс, 13 группа,"
    				+ " ФПМИ, БГУ.</p>");
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
       
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String s1 = "";
        if ((String)jComboBox1.getSelectedItem()=="Дата поступления") { 
            s1="d";
        }
        else if ((String)jComboBox1.getSelectedItem()=="Поставщик") { 
            s1="p";
        }
        else if ((String)jComboBox1.getSelectedItem()== "Возрастные ограничения") { 
            s1="a";
        }
        
        if ((String)jComboBox2.getSelectedItem()=="Очистить данные по ключу") { //clear data by key
            String[] tmp = {"", s1, jTextField1.getText()};
            try {
                Serialization.deleteFile(tmp);
            } catch (Exception ex){
            }
        }
        else if ((String)jComboBox2.getSelectedItem()=="Печать несортированных данных") { //print data unsorted
            try{
                Serialization.printFile();
            } catch (Exception ex) {
            }
            JFrame output = new Output(Serialization.output);
            output.setVisible(true);
        }
        else if ((String)jComboBox2.getSelectedItem()== "Добавить данные") { //append data
            JFrame app = new NewJFrame2(false);
            app.setVisible(true);
        }
        else if ((String)jComboBox2.getSelectedItem()=="Добавление сжатых данных") { //append and compress data
            JFrame app = new NewJFrame2(true);
            app.setVisible(true);
        }
        else if ((String)jComboBox2.getSelectedItem()=="Очистить все данные") { //clear all data
            Serialization.deleteFile();
            JOptionPane.showMessageDialog(this, "Данные удалены!"); 
        }
        else if ((String)jComboBox2.getSelectedItem()=="Распечатать отсортированные данные по ключу") { //print data sorted by key
            String[] tmp = {"", s1};
            try {
                Serialization.printFile(tmp, false);
            } catch (Exception ex){
            }
            JFrame output = new Output(Serialization.output);
            output.setVisible(true);
        }
        else if ((String)jComboBox2.getSelectedItem()=="Печать данных в обратном порядке отсортированных по ключу") { //print data sorted by key and reversed
            String[] tmp = {"", s1};
            try {
                Serialization.printFile(tmp, true);
            } catch (Exception ex){
            }
            JFrame output = new Output(Serialization.output);
            output.setVisible(true);
        }
        else if ((String)jComboBox2.getSelectedItem()=="Найти запись по ключу") { //find record by key
            String[] tmp = {"", s1, jTextField1.getText()};
            try {
                Serialization.findByKey(tmp);
            } catch (Exception ex){
            }
            JFrame output = new Output(Serialization.output);
            output.setVisible(true);
        }
        else if ((String)jComboBox2.getSelectedItem()=="Найти запись < ключу") { //find record greater than key
            String[] tmp = {"", s1, jTextField1.getText()};
            try {
                Serialization.findByKey(tmp, new KeyCompReverse());
            } catch (Exception ex){
            }
            JFrame output = new Output(Serialization.output);
            output.setVisible(true);
        }
        else if ((String)jComboBox2.getSelectedItem()=="Найти запись > ключу") { //find record less than key
            String[] tmp = {"",s1, jTextField1.getText()};
            try {
                Serialization.findByKey(tmp, new KeyComp());
            } catch (Exception ex){
            }
            JFrame output = new Output(Serialization.output);
            output.setVisible(true);
        }
        else { 
            JOptionPane.showMessageDialog(this, "Способ не выбран!"); 
        }
        jTextField1.setText("");
        Serialization.output = "";
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
        FontChooser chooser = new FontChooser(this);
        chooser.setVisible(true);
    	Font font = chooser.getSelectedFont();
        if (font != null) {
            java.util.Enumeration keys = UIManager.getLookAndFeelDefaults().keys();
            while (keys.hasMoreElements()) {
                Object key = keys.nextElement();
                Object value = UIManager.get (key);
                if (value instanceof FontUIResource) {
                    UIManager.getLookAndFeelDefaults().put(key, new FontUIResource(font));
                    SwingUtilities.updateComponentTreeUI(this);
                    UIManager.put("Button.font", font);
                    UIManager.put("ToggleButton.font", font);
                    UIManager.put("RadioButton.font", font);
                    UIManager.put("CheckBox.font", font);
                    UIManager.put("ColorChooser.font", font);
                    UIManager.put("ComboBox.font", font);
                    UIManager.put("Label.font", font);
                    UIManager.put("List.font", font);
                    UIManager.put("MenuBar.font", font);
                    UIManager.put("MenuItem.font", font);
                    UIManager.put("RadioButtonMenuItem.font", font);
                    UIManager.put("CheckBoxMenuItem.font", font/* font of your liking */);
                    UIManager.put("Menu.font", font/* font of your liking */);
                    UIManager.put("PopupMenu.font", font/* font of your liking */);
                    UIManager.put("OptionPane.font", font/* font of your liking */);
                    UIManager.put("Panel.font", font/* font of your liking */);
                    UIManager.put("ProgressBar.font", font/* font of your liking */);
                    UIManager.put("ScrollPane.font", font/* font of your liking */);
                    UIManager.put("Viewport.font", font/* font of your liking */);
                    UIManager.put("TabbedPane.font", font/* font of your liking */);
                    UIManager.put("Table.font", font/* font of your liking */);
                    UIManager.put("TableHeader.font", font/* font of your liking */);
                    UIManager.put("TextField.font", font/* font of your liking */);
                    UIManager.put("PasswordField.font", font/* font of your liking */);
                    UIManager.put("TextArea.font", font/* font of your liking */);
                    UIManager.put("TextPane.font", font/* font of your liking */);
                    UIManager.put("EditorPane.font", font/* font of your liking */);
                    UIManager.put("TitledBorder.font", font/* font of your liking */);
                    UIManager.put("ToolBar.font", font/* font of your liking */);
                    UIManager.put("ToolTip.font", font/* font of your liking */);
                    UIManager.put("Tree.font", font/* font of your liking */);
                    this.setFont(font);
                    SwingUtilities.updateComponentTreeUI(this);
                }
            }
        }
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed
    private boolean lookandfeelindex = false;   
    private void jMenu4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseEntered
        if (!lookandfeelindex) {
            lookandfeelindex = true;
            ButtonGroup radiogroup = new ButtonGroup();  

            // Look up the available look and feels
            UIManager.LookAndFeelInfo[] plafs =
                UIManager.getInstalledLookAndFeels();

            // Loop through the plafs, and add a menu item for each one
            for(int i = 0; i < plafs.length; i++) {
                String plafName = plafs[i].getName();
                final String plafClassName = plafs[i].getClassName();

                // Create the menu item
                JMenuItem item = jMenu4.add(new JRadioButtonMenuItem(plafName));

                // Tell the menu item what to do when it is selected
                item.addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent e) {
                            try {
                                // Set the new look and feel
                                UIManager.setLookAndFeel(plafClassName);
                                // Tell each component to change its look-and-feel
                                SwingUtilities.updateComponentTreeUI(NewJFrame.this);
                                // Tell the frame to resize itself to the its
                                // children's new desired sizes
                                //frame.pack();
                            }
                            catch(Exception ex) { System.err.println(ex); }
                        }

                    });

                // Only allow one menu item to be selected at once
                radiogroup.add(item);
            }
        }
    }//GEN-LAST:event_jMenu4MouseEntered

    private void jRadioButtonMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem4ActionPerformed
        JFrame fname = new ChangeFileName();
        fname.setVisible(true);      
    }//GEN-LAST:event_jRadioButtonMenuItem4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         JFrame fname = new ChangeFileName();
        fname.setVisible(true);  
    }//GEN-LAST:event_jButton2ActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
