import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.FontUIResource;

public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apartments");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Append data");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Append and compress data");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Clear all data");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Clear data by key");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Print data unsorted");

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Print data sorted by key");

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("Print data sorted by key and reversed");

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("Find record by key");

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setText("Find record greater than key");

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setText("Find record less than key");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Needed input:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem2.setText("Change file name");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("Quit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("View");

        jMenuItem1.setText("Font");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenu4.setText("Look and Feel");
        jMenu4.setHideActionText(true);
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenu4MouseEntered(evt);
            }
        });
        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem3.setText("About");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jRadioButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Font    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FontChooser chooser = new FontChooser(GUI.this);
        chooser.setVisible(true);
    	Font font = chooser.getSelectedFont();
        if (font != null) {
            java.util.Enumeration keys = UIManager.getLookAndFeelDefaults().keys();
            while (keys.hasMoreElements()) {
                Object key = keys.nextElement();
                Object value = UIManager.get (key);
                if (value instanceof FontUIResource) {
                    UIManager.getLookAndFeelDefaults().put(key, new FontUIResource(font));
                    SwingUtilities.updateComponentTreeUI(GUI.this);
                    UIManager.put("Button.font", font);
                    UIManager.put("ToggleButton.font", font);
                    UIManager.put("RadioButton.font", font);
                    UIManager.put("CheckBox.font", font);
                    UIManager.put("ColorChooser.font", font);
                    UIManager.put("ComboBox.font", font);
                    UIManager.put("Label.font", font);
                    UIManager.put("List.font", font);
                    UIManager.put("MenuBar.font", font);
                    UIManager.put("MenuItem.font", font);
                    UIManager.put("RadioButtonMenuItem.font", font);
                    UIManager.put("CheckBoxMenuItem.font", font/* font of your liking */);
                    UIManager.put("Menu.font", font/* font of your liking */);
                    UIManager.put("PopupMenu.font", font/* font of your liking */);
                    UIManager.put("OptionPane.font", font/* font of your liking */);
                    UIManager.put("Panel.font", font/* font of your liking */);
                    UIManager.put("ProgressBar.font", font/* font of your liking */);
                    UIManager.put("ScrollPane.font", font/* font of your liking */);
                    UIManager.put("Viewport.font", font/* font of your liking */);
                    UIManager.put("TabbedPane.font", font/* font of your liking */);
                    UIManager.put("Table.font", font/* font of your liking */);
                    UIManager.put("TableHeader.font", font/* font of your liking */);
                    UIManager.put("TextField.font", font/* font of your liking */);
                    UIManager.put("PasswordField.font", font/* font of your liking */);
                    UIManager.put("TextArea.font", font/* font of your liking */);
                    UIManager.put("TextPane.font", font/* font of your liking */);
                    UIManager.put("EditorPane.font", font/* font of your liking */);
                    UIManager.put("TitledBorder.font", font/* font of your liking */);
                    UIManager.put("ToolBar.font", font/* font of your liking */);
                    UIManager.put("ToolTip.font", font/* font of your liking */);
                    UIManager.put("Tree.font", font/* font of your liking */);
                    this.setFont(font);
                    SwingUtilities.updateComponentTreeUI(this);
                }
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    //About
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JOptionPane.showMessageDialog(GUI.this, "<html><h2>Условие задачи:</h2>"
    				+ "<p>Запись о квартире имеет атрибуты: номер квартиры, площадь, этаж, "
    				+ "количество комнат, улица, тип здания, срок эксплуатации.</p>"
    				+ "<p>Индексировать по: номер квартиры, площадь, этаж, срок эксплуатации.</p>"
    				+ "<h2>Информация о разработчике:</h2><p>Булах Артём Игоревич, 13 группа, 2 курс,"
    				+ " ФПМИ, БГУ.</p>");
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    //Quit
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        int response = JOptionPane.showConfirmDialog(GUI.this, "Really Quit?");
    	if (response == JOptionPane.YES_OPTION) System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    //Look and Feel
    private boolean lookandfeelindex = false;
    private void jMenu4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseEntered
        if (!lookandfeelindex) {
            lookandfeelindex = true;
            ButtonGroup radiogroup = new ButtonGroup();  

            // Look up the available look and feels
            UIManager.LookAndFeelInfo[] plafs =
                UIManager.getInstalledLookAndFeels();

            // Loop through the plafs, and add a menu item for each one
            for(int i = 0; i < plafs.length; i++) {
                String plafName = plafs[i].getName();
                final String plafClassName = plafs[i].getClassName();

                // Create the menu item
                JMenuItem item = jMenu4.add(new JRadioButtonMenuItem(plafName));

                // Tell the menu item what to do when it is selected
                item.addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent e) {
                            try {
                                // Set the new look and feel
                                UIManager.setLookAndFeel(plafClassName);
                                // Tell each component to change its look-and-feel
                                SwingUtilities.updateComponentTreeUI(GUI.this);
                                // Tell the frame to resize itself to the its
                                // children's new desired sizes
                                //frame.pack();
                            }
                            catch(Exception ex) { System.err.println(ex); }
                        }

                    });

                // Only allow one menu item to be selected at once
                radiogroup.add(item);
            }
        }
    }//GEN-LAST:event_jMenu4MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jRadioButton1.isSelected()) { //clear data by key
            String[] tmp = {"", jTextField1.getText().substring(0, 1), jTextField1.getText().substring(2)};
            try {
                ApartmentSerialization.deleteFile(tmp);
            } catch (Exception ex){
            }
        }
        else if (jRadioButton2.isSelected()) { //print data unsorted
            try{
                ApartmentSerialization.printFile();
            } catch (Exception ex) {
            }
            JFrame output = new Output(ApartmentSerialization.output);
            output.setVisible(true);
        }
        else if (jRadioButton3.isSelected()) { //append data
            JFrame app = new Append(false);
            app.setVisible(true);
        }
        else if (jRadioButton4.isSelected()) { //append and compress data
            JFrame app = new Append(true);
            app.setVisible(true);
        }
        else if (jRadioButton5.isSelected()) { //clear all data
            ApartmentSerialization.deleteFile();
            JOptionPane.showMessageDialog(GUI.this, "Data was deleted!"); 
        }
        else if (jRadioButton6.isSelected()) { //print data sorted by key
            String[] tmp = {"", jTextField1.getText()};
            try {
                ApartmentSerialization.printFile(tmp, false);
            } catch (Exception ex){
            }
            JFrame output = new Output(ApartmentSerialization.output);
            output.setVisible(true);
        }
        else if (jRadioButton7.isSelected()) { //print data sorted by key and reversed
            String[] tmp = {"", jTextField1.getText()};
            try {
                ApartmentSerialization.printFile(tmp, true);
            } catch (Exception ex){
            }
            JFrame output = new Output(ApartmentSerialization.output);
            output.setVisible(true);
        }
        else if (jRadioButton8.isSelected()) { //find record by key
            String[] tmp = {"", jTextField1.getText().substring(0, 1), jTextField1.getText().substring(2)};
            try {
                ApartmentSerialization.findByKey(tmp);
            } catch (Exception ex){
            }
            JFrame output = new Output(ApartmentSerialization.output);
            output.setVisible(true);
        }
        else if (jRadioButton9.isSelected()) { //find record greater than key
            String[] tmp = {"", jTextField1.getText().substring(0, 1), jTextField1.getText().substring(2)};
            try {
                ApartmentSerialization.findByKey(tmp, new KeyCompReverse());
            } catch (Exception ex){
            }
            JFrame output = new Output(ApartmentSerialization.output);
            output.setVisible(true);
        }
        else if (jRadioButton10.isSelected()) { //find record less than key
            String[] tmp = {"", jTextField1.getText().substring(0, 1), jTextField1.getText().substring(2)};
            try {
                ApartmentSerialization.findByKey(tmp, new KeyComp());
            } catch (Exception ex){
            }
            JFrame output = new Output(ApartmentSerialization.output);
            output.setVisible(true);
        }
        else { 
            JOptionPane.showMessageDialog(GUI.this, "No option selected!"); 
        }
        jTextField1.setText("");
        ApartmentSerialization.output = "";
    }//GEN-LAST:event_jButton1ActionPerformed
    //change file name
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFrame fname = new ChangeFileName();
        fname.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
